# Generated by Django 5.0.6 on 2024-06-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='abc', max_length=100)),
                ('password', models.CharField(default='abc', max_length=100)),
                ('email', models.EmailField(default='abc@gmail.com', max_length=254)),
                ('image', models.ImageField(upload_to='user_images/')),
                ('description', models.TextField()),
                ('hash', models.CharField(max_length=256)),
            ],
        ),
    ]
