# Generated by Django 5.0.6 on 2024-06-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPreference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('job_code', models.CharField(max_length=6)),
            ],
        ),
    ]
