# Generated by Django 5.0.6 on 2024-06-21 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_jobpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpted',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jobid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobpreference')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
