# Generated by Django 5.0.6 on 2024-06-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='course',
        ),
        migrations.RemoveField(
            model_name='person',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='person',
        ),
        migrations.AddField(
            model_name='user',
            name='qualification',
            field=models.CharField(default='engineer', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
