# Generated by Django 5.0.6 on 2024-06-25 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_user_hash'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobopted',
            unique_together={('user_id', 'jobid')},
        ),
    ]
